import {useEffect,useState} from 'react';
import {tokens} from '@quekou/theme';
import {ArrowLeft,ArrowUpRight,Layers3,RotateCcw} from 'lucide-react';
import {ThemeProvider,Button,Select,type ThemeName,type ThemeSettings,normalizeTheme} from '@quekou/ui';
import {componentGroups} from './component-examples';
import './component-lab.css';
const themes=[{id:'bento',number:6,label:'Bento',description:'清晰分区'},{id:'glass',number:7,label:'Glass',description:'轻透层次'},{id:'ambient',number:10,label:'Ambient',description:'安静聚焦'}] as const;
function initialSettings(){const p=new URLSearchParams(location.search),chosen=themes.find(t=>String(t.number)===p.get('style'))||themes[0];return normalizeTheme({theme:chosen.id,accentHue:p.get('accentHue')==='brand'||!p.has('accentHue')?'brand':Number(p.get('accentHue')),density:p.get('density') as ThemeSettings['density'],radiusScale:Number(p.get('radiusScale')) as ThemeSettings['radiusScale'],surfaceMode:(p.get('surfaceMode')||p.get('mode')) as ThemeSettings['surfaceMode']});}
export default function ComponentLab(){
 const [settings,setSettings]=useState(initialSettings);
 const theme=themes.find(t=>t.id===settings.theme)!;
 const patch=(next:Partial<ThemeSettings>)=>setSettings(current=>normalizeTheme({...current,...next}));
 useEffect(()=>{const p=new URLSearchParams({view:'components',style:String(themes.find(t=>t.id===settings.theme)!.number),accentHue:String(settings.accentHue),density:settings.density,radiusScale:String(settings.radiusScale),surfaceMode:settings.surfaceMode});history.replaceState({},'',location.pathname+'?'+p+location.hash);document.title='缺口 · 组件验收 / 阶段 03';},[settings]);
 return <ThemeProvider {...settings} className="component-lab gallery-workspace">
  <div className="lab-frame">
   <header className="lab-topbar"><a href={`/?style=${theme.number}&accentHue=${settings.accentHue}&density=${settings.density}&radiusScale=${settings.radiusScale}&surfaceMode=${settings.surfaceMode}`}><ArrowLeft className="qk-icon"/>返回工作台预览</a><span>QUEKOU / 缺口 · 工作台视觉系统</span><span className="lab-stage">阶段 03 · 已认可</span></header>
   <section className="lab-intro"><div><p className="qk-eyebrow">COMPONENT LIBRARY / 可复用组件</p><h1>一种视觉标准，<br/>贯穿每一次操作。</h1><p className="lab-lead">将已认可的视觉规范落到具体控件。切换主题，点击、输入和选择，检查日常使用是否顺手。</p><nav aria-label="组件分类" className="lab-jump">{componentGroups.map(g=><a key={g.id} href={'#'+g.id}>{g.title}<span>{g.items.length}</span><ArrowUpRight className="qk-icon"/></a>)}</nav></div><aside className="lab-summary"><Layers3 aria-hidden="true"/><strong>28</strong><p>组件 · 三套主题共用</p><div><span>12 基础控件</span><span>10 数据展示</span><span>06 工作台结构</span></div></aside></section>
   <section className="lab-settings" aria-label="组件主题设置"><div className="lab-settings-heading"><div><h2>选择你的查看方式</h2><p className="qk-muted">保留缺口品牌色，沿用已确认的四项调整范围。</p></div><Button size="sm" onClick={()=>setSettings(normalizeTheme({theme:settings.theme}))}><RotateCcw className="qk-icon"/>恢复默认值</Button></div><div className="lab-theme-tabs" role="group" aria-label="组件主题">{themes.map(t=><button key={t.id} type="button" aria-pressed={settings.theme===t.id} onClick={()=>patch({theme:t.id as ThemeName})}><span>{String(t.number).padStart(2,'0')}</span><strong>{t.label}</strong><small>{t.description}</small></button>)}</div><div className="lab-controls"><label className="qk-field"><span className="qk-label">强调色相</span><div className="lab-hue"><input type="range" min={tokens.parameterPolicy.accentHue.minimum} max={tokens.parameterPolicy.accentHue.maximum} step={tokens.parameterPolicy.accentHue.step} aria-label="组件强调色相" value={settings.accentHue==='brand'?Math.round(tokens.parameterPolicy.accentHue.default):settings.accentHue} onChange={e=>patch({accentHue:Number(e.target.value)})}/><output>{settings.accentHue==='brand'?'缺口标准蓝':settings.accentHue+'°'}</output></div><button className="lab-brand-reset" onClick={()=>patch({accentHue:'brand'})}>恢复标准蓝</button></label><Select label="组件信息密度" value={settings.density} onChange={e=>patch({density:e.target.value as ThemeSettings['density']})} options={[{value:'comfortable',label:'舒适 · 留白更多'},{value:'compact',label:'紧凑 · 同屏更多'}]}/><Select label="组件圆角程度" value={settings.radiusScale} onChange={e=>patch({radiusScale:Number(e.target.value) as ThemeSettings['radiusScale']})} options={[{value:'0.5',label:'0.5× · 更利落'},{value:'1',label:'1× · 标准'},{value:'1.5',label:'1.5× · 更柔和'}]}/><Select label="组件明暗模式" value={settings.surfaceMode} onChange={e=>patch({surfaceMode:e.target.value as ThemeSettings['surfaceMode']})} options={[{value:'light',label:'浅色'},{value:'dark',label:'深色'},{value:'auto',label:'跟随系统'}]}/></div></section>
   <main>{componentGroups.map((group,groupIndex)=><section key={group.id} id={group.id} className="lab-group" aria-labelledby={group.id+'-title'}><header className="lab-group-heading"><span>{String(groupIndex+1).padStart(2,'0')}</span><div><h2 id={group.id+'-title'}>{group.title}<small>{group.items.length} 个组件</small></h2><p>{group.description}</p></div></header><div className="lab-component-grid">{group.items.map(({name,label,Example,wide},i)=><article key={name} id={'component-'+name} className="lab-component" data-wide={wide}><header><div><h3>{label}</h3><span>{name}</span></div><small>{String(i+1).padStart(2,'0')}</small></header><div className="lab-example"><Example/></div></article>)}</div></section>)}</main>
   <footer className="lab-footer"><strong>本页用于组件验收</strong><p>全部业务数字为演示数据。组件已认可，可继续检查完整业务页面。</p><a href={`/?view=recipes&style=${theme.number}&accentHue=${settings.accentHue}&density=${settings.density}&radiusScale=${settings.radiusScale}&surfaceMode=${settings.surfaceMode}`}>进入第四阶段 · 页面模板 →</a></footer>
  </div>
 </ThemeProvider>;
}
