import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {fileURLToPath} from 'node:url';import {execFileSync} from 'node:child_process';import {createHash} from 'node:crypto';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');process.chdir(root);
const pkg=JSON.parse(fs.readFileSync('package.json','utf8')),version=pkg.version,label='quekou-workbench-'+version;
const npm=process.env.npm_execpath;const runNpm=args=>npm?execFileSync(process.execPath,[npm,...args],{stdio:'pipe'}):execFileSync(process.platform==='win32'?'npm.cmd':'npm',args,{stdio:'pipe'});
fs.mkdirSync('artifacts',{recursive:true});
for(const name of ['theme','ui']){fs.copyFileSync('LICENSE.txt','packages/'+name+'/LICENSE.txt');const p=JSON.parse(fs.readFileSync('packages/'+name+'/package.json','utf8'));if(p.version!==version)throw Error('Package versions must match');runNpm(['pack','./packages/'+name,'--pack-destination','artifacts','--cache',path.join(os.tmpdir(),'quekou-npm-cache')]);}
if(process.argv.includes('--packages-only')){console.log('Packed '+version+' theme/ui');process.exit(0);}
for(const report of ['qa/phase3/browser-report.json','qa/phase4/browser-report.json','qa/release/hardening-report.json','qa/release/npm-audit.json']){if(!fs.existsSync(report))throw Error('Missing release evidence '+report);const r=JSON.parse(fs.readFileSync(report,'utf8'));if(report.endsWith('npm-audit.json')?r.metadata?.vulnerabilities?.total!==0:r.result!=='passed')throw Error('Evidence is not passing '+report);}
execFileSync(process.execPath,['scripts/build-guide.mjs'],{stdio:'inherit'});
fs.mkdirSync('materials/previews',{recursive:true});
for(const style of [6,7,10])for(const page of ['overview','list','detail','settings'])fs.copyFileSync('qa/phase4/'+style+'-'+page+'.png','materials/previews/'+style+'-'+page+'.png');
const licenses=[];fs.mkdirSync('materials/licenses',{recursive:true});
const inspect=dir=>{for(const name of fs.readdirSync(dir)){if(name.startsWith('.'))continue;const p=path.join(dir,name);if(fs.lstatSync(p).isSymbolicLink())continue;if(name.startsWith('@')){inspect(p);continue;}const meta=path.join(p,'package.json');if(!fs.existsSync(meta))continue;const m=JSON.parse(fs.readFileSync(meta,'utf8'));const texts=fs.readdirSync(p).filter(n=>/^(licen[sc]e|copying|notice)(\.|$)/i.test(n)&&fs.statSync(path.join(p,n)).isFile());const copied=texts.map(f=>{const dest=(m.name+'-'+m.version+'-'+f).replaceAll('/','__');fs.copyFileSync(path.join(p,f),path.join('materials/licenses',dest));return 'licenses/'+dest;});licenses.push({name:m.name,version:m.version,license:m.license||'see package metadata',texts:copied});if(fs.existsSync(path.join(p,'node_modules')))inspect(path.join(p,'node_modules'));}};
inspect('node_modules');fs.writeFileSync('materials/dependencies.json',JSON.stringify(licenses.sort((a,b)=>a.name.localeCompare(b.name)),null,2)+'\n');
const scratch=fs.mkdtempSync(path.join(os.tmpdir(),'quekou-release-')),stage=path.join(scratch,label);fs.mkdirSync(stage);
const roots=['AGENTS.md','README.md','START_HERE.md','START_HERE.html','NEW_CLIENT.md','RELEASE_AUDIT.md','LICENSE.txt','THIRD_PARTY_NOTICES.md','package.json','package-lock.json','index.html','tsconfig.json','vite.config.ts','tailwind.config.cjs','postcss.config.cjs','.gitignore','app','design','packages','starter','scripts','docs','materials','.agents/skills'];
for(const p of roots)fs.cpSync(p,path.join(stage,p),{recursive:true,filter:s=>!s.split(path.sep).includes('node_modules')});
for(const p of ['theme','ui']){fs.mkdirSync(path.join(stage,'artifacts'),{recursive:true});fs.copyFileSync('artifacts/quekou-'+p+'-'+version+'.tgz',path.join(stage,'artifacts/quekou-'+p+'-'+version+'.tgz'));}
const qaFiles=['check-guide.cjs','check-client-browser.cjs','release/guide-report.json','release/client-browser-report.json','browser-runtime.cjs','browser-contrast.cjs','check-phase3.cjs','check-phase4.cjs','check-release-browser.cjs','check-token-contract.mjs','token-audit.mjs','check-phase4-model.mjs','phase3/browser-report.json','phase4/browser-report.json','phase4/model-report.json','release/hardening-report.json','release/npm-audit.json','release/portability-report.json','token-report.json','phase5-token-contract-report.json'];
for(const p of qaFiles){if(!fs.existsSync('qa/'+p))continue;fs.mkdirSync(path.dirname(path.join(stage,'qa',p)),{recursive:true});fs.copyFileSync('qa/'+p,path.join(stage,'qa',p));}
const walk=dir=>fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>{const p=path.join(dir,e.name);if(e.isSymbolicLink())throw Error('No symlinks in release');return e.isDirectory()?walk(p):[p];});
const files=walk(stage).sort();for(const p of files){if(/\.(md|json|mjs|cjs|tsx?|html|css)$/.test(p)&&fs.readFileSync(p,'utf8').includes(['','Users',''].join('/')))throw Error('Nonportable personal path in '+p);}
const sum=files.map(p=>createHash('sha256').update(fs.readFileSync(p)).digest('hex')+'  '+path.relative(stage,p).split(path.sep).join('/')).join('\n')+'\n';fs.writeFileSync(path.join(stage,'SHA256SUMS.txt'),sum);
execFileSync(process.execPath,[path.join(stage,'scripts/verify-release.mjs')],{stdio:'inherit'});
fs.mkdirSync('releases',{recursive:true});const zip=path.join(root,'releases',label+'.zip');
const python=process.env.PYTHON||(process.platform==='win32'?'python':'python3');
execFileSync(python,['-c','import pathlib,sys,zipfile\nroot=pathlib.Path(sys.argv[1]);target=pathlib.Path(sys.argv[2])\nwith zipfile.ZipFile(target,"w",zipfile.ZIP_DEFLATED,compresslevel=9) as z:\n for p in sorted(root.rglob("*")):\n  if p.is_file(): z.write(p,p.relative_to(root.parent))',stage,zip],{stdio:'inherit'});
const hash=createHash('sha256').update(fs.readFileSync(zip)).digest('hex');fs.writeFileSync(zip+'.sha256',hash+'  '+path.basename(zip)+'\n');console.log(JSON.stringify({zip,bytes:fs.statSync(zip).size,sha256:hash,files:files.length+1},null,2));fs.rmSync(scratch,{recursive:true,force:true});
