import {projects as initialProjects,type Project,type ProjectStatus} from '../data';
import type {TableSort,StatusKind,TrendPoint,ActivityItem} from '@quekou/ui';
export interface WorkProject extends Project {signedMonth:string}
const monthIndex=[4,5,5,1,3,2,5,0,4,3];
export const initialWorkProjects:WorkProject[]=initialProjects.map((p,i)=>({...p,signedMonth:`2026-${String(monthIndex[i]+4).padStart(2,'0')}`}));
export const stages:ProjectStatus[]=['正常推进','存在风险','待验收','已完成'];
export const statusTone:Record<ProjectStatus,StatusKind>={'正常推进':'info','存在风险':'warning','待验收':'info','已完成':'success'};
export interface QueryState {search:string;status:string;client:string;from:string;to:string}
export const emptyQuery:QueryState={search:'',status:'all',client:'all',from:'',to:''};
export function selectProjects(rows:readonly WorkProject[],query:QueryState,sort:TableSort|null){const needle=query.search.trim().toLocaleLowerCase();const result=rows.filter(p=>(query.status==='all'||p.status===query.status)&&(query.client==='all'||p.client===query.client)&&(!query.from||p.due>=query.from)&&(!query.to||p.due<=query.to)&&(!needle||[p.id,p.name,p.client,p.owner,p.status].some(v=>v.toLocaleLowerCase().includes(needle))));if(sort){const key=sort.column as keyof WorkProject;result.sort((a,b)=>{const av=a[key],bv=b[key];const result=typeof av==='number'&&typeof bv==='number'?av-bv:String(av??'').localeCompare(String(bv??''),'zh-CN',{numeric:true});return sort.direction==='asc'?result:-result;});}return result;}
export const totals=(rows:readonly WorkProject[])=>({amount:rows.reduce((s,p)=>s+p.amount,0),count:rows.length,average:rows.length?rows.reduce((s,p)=>s+p.progress,0)/rows.length:0,risks:rows.filter(p=>p.status==='存在风险').length,completed:rows.filter(p=>p.status==='已完成').length});
export const trend=(rows:readonly WorkProject[]):TrendPoint[]=>Array.from({length:6},(_,i)=>{const month=`2026-${String(i+4).padStart(2,'0')}`;return {label:`${i+4}月`,value:+(rows.filter(p=>p.signedMonth===month).reduce((s,p)=>s+p.amount,0)/10000).toFixed(1),target:[10,12,14,22,30,55][i]};});
export function timeline(project:WorkProject):ActivityItem[]{if(project.id.startsWith('QK-DEMO-'))return [{id:'created',title:'创建演示项目',detail:'新项目尚未填写交付进展。',actor:project.owner,time:'2026-09-28',status:'info',statusLabel:'已创建'}];return [{id:'kickoff',title:'确认项目范围',detail:'以需求清单确定本次交付范围和验收对象。',actor:project.owner,time:'2026-08-18 10:00',status:'success',statusLabel:'已记录'},{id:'review',title:'完成阶段方案复核',detail:'演示记录：按约定的交付节点推进实施。',actor:project.owner,time:'2026-09-04 15:30',status:'success',statusLabel:'已记录'},{id:'update',title:`进度更新至 ${project.progress}%`,detail:project.status==='存在风险'?'演示风险：待客户补齐现场数据，负责人需复核交付计划。':project.status==='待验收'?'演示记录：材料已进入验收准备，等待负责人复核。':project.status==='已完成'?'演示记录：本项目已完成验收。':'演示记录：当前按计划推进，继续跟踪下一交付节点。',actor:project.owner,time:(project.status==='已完成'?project.due:'2026-09-28')+' 09:30',status:statusTone[project.status],statusLabel:project.status}];}
export interface RelatedItem {id:string;name:string;kind:string;owner:string;state:string}
export function relatedRecords(project:WorkProject):RelatedItem[]{if(project.id.startsWith('QK-DEMO-'))return [];return [{id:project.id+'-01',name:'需求范围确认单',kind:'范围记录',owner:project.owner,state:'已确认'},{id:project.id+'-02',name:'阶段交付清单',kind:'交付记录',owner:project.owner,state:project.progress>=60?'已复核':'待复核'},{id:project.id+'-03',name:'客户验收记录',kind:'验收记录',owner:project.owner,state:project.status==='已完成'?'已确认':'待复核'}];}
export interface WorkspaceSettings {workspaceName:string;manager:string;timezone:string;digest:boolean;riskAlerts:boolean}
export const defaultSettings:WorkspaceSettings={workspaceName:'缺口 · 项目交付工作区',manager:'林悦',timezone:'Asia/Shanghai',digest:true,riskAlerts:true};
export const settingsKey='quekou-workbench-phase4-settings-v1';
export function readSettings():WorkspaceSettings {try{const v=JSON.parse(localStorage.getItem(settingsKey)||'null');return v&&typeof v.workspaceName==='string'&&v.workspaceName.trim()&&['林悦','周明','陈曦','许诺'].includes(v.manager)&&['Asia/Shanghai','UTC'].includes(v.timezone)&&typeof v.digest==='boolean'&&typeof v.riskAlerts==='boolean'?v:defaultSettings;}catch{return defaultSettings;}}
