import {useState,useEffect,useRef,type MouseEvent} from 'react';
import {LayoutDashboard,FolderKanban,FileText,Settings2,Plus,ArrowLeft,ArrowUpRight,SlidersHorizontal,Command,CheckCircle2,RotateCcw,Layers3} from 'lucide-react';
import {tokens} from '@quekou/theme';
import {ThemeProvider,normalizeTheme,AppShell,NavGroup,Avatar,Button,Badge,Select,Input,Dialog,Toast,CommandPalette,Overview,List,Detail,Settings,ProgressBar,recipeCatalog,type RecipeId,type DataColumn,type KpiRowProps,type SettingsSectionProps,type ThemeSettings} from '@quekou/ui';
import {initialWorkProjects,selectProjects,totals,trend,timeline,relatedRecords,statusTone,stages,emptyQuery,defaultSettings,readSettings,settingsKey,type WorkProject,type RelatedItem,type WorkspaceSettings,type QueryState} from './model';
import {readRoute,routeUrl,styleOptions,type WorkbenchRoute} from './route';
import './workbench.css';
const pageIcons={overview:LayoutDashboard,list:FolderKanban,detail:FileText,settings:Settings2};
const owners=['林悦','周明','陈曦','许诺'];
export default function WorkbenchDemo(){
 const [route,setRoute]=useState(readRoute),[rows,setRows]=useState(initialWorkProjects),[selection,setSelection]=useState<readonly string[]>([]),[collapsed,setCollapsed]=useState(false);
 const [dataState,setDataState]=useState<'ready'|'loading'|'empty'>('ready'),[commandOpen,setCommandOpen]=useState(false),[newOpen,setNewOpen]=useState(false),[relatedOpen,setRelatedOpen]=useState<RelatedItem|null>(null);
 const [saved,setSaved]=useState(readSettings),[draft,setDraft]=useState<WorkspaceSettings>(readSettings),[settingsGroup,setSettingsGroup]=useState('workspace-info'),[settingsError,setSettingsError]=useState(''),[saveMessage,setSaveMessage]=useState('已载入浏览器中的演示配置');
 const [toast,setToast]=useState(''),[newName,setNewName]=useState(''),[newClient,setNewClient]=useState(initialWorkProjects[0].client),[newOwner,setNewOwner]=useState(saved.manager),[newAmount,setNewAmount]=useState('100000'),[newDue,setNewDue]=useState('2026-10-30'),[newError,setNewError]=useState('');
 const mainRef=useRef<HTMLDivElement>(null),priorPage=useRef(route.page);
 const dirty=JSON.stringify(saved)!==JSON.stringify(draft);
 const patch=(next:Partial<WorkbenchRoute>)=>setRoute(current=>({...current,...next}));
 const navigate=(page:RecipeId,extra:Partial<WorkbenchRoute>={})=>{const next={...route,...extra,page};history.pushState({},'',routeUrl(next));setRoute(next);};
 useEffect(()=>{history.replaceState({},'',routeUrl(route));document.title=`${recipeCatalog.find(p=>p.id===route.page)!.label} · 缺口工作台`;},[route]);
 useEffect(()=>{const handler=()=>setRoute(readRoute());addEventListener('popstate',handler);return()=>removeEventListener('popstate',handler);},[]);
 useEffect(()=>{if(priorPage.current!==route.page){mainRef.current?.focus({preventScroll:true});scrollTo({top:0,behavior:'instant'});priorPage.current=route.page;}},[route.page]);
 useEffect(()=>{if(!dirty)return;const guard=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};addEventListener('beforeunload',guard);return()=>removeEventListener('beforeunload',guard);},[dirty]);
 const themed=(next:Partial<ThemeSettings>)=>patch({settings:normalizeTheme({...route.settings,...next})});
 const theme=route.settings.theme,sourceRows=dataState==='ready'?rows:[],summary=totals(sourceRows),filtered=selectProjects(sourceRows,route.query,route.sort),pageCount=Math.ceil(filtered.length/route.pageSize),currentPage=Math.max(1,Math.min(route.listPage,pageCount||1)),pageRows=filtered.slice((currentPage-1)*route.pageSize,currentPage*route.pageSize);
 const activeProject=dataState==='ready'?rows.find(r=>r.id===route.recordId):undefined;
 const clientNames=[...new Set(rows.map(p=>p.client))];
 const query=(next:Partial<QueryState>)=>patch({query:{...route.query,...next},listPage:1});
 const openProject=(id:string)=>navigate('detail',{recordId:id,tab:'timeline'});
 const openStatus=(status:string)=>navigate('list',{query:{...emptyQuery,status},listPage:1});
 const columns:DataColumn<WorkProject>[]=[{id:'name',label:'项目名称',value:p=>p.name,render:p=><Button variant="ghost" size="sm" onClick={()=>openProject(p.id)}>{p.name}</Button>},{id:'client',label:'客户',value:p=>p.client},{id:'owner',label:'负责人',value:p=>p.owner},{id:'status',label:'状态',value:p=>p.status,render:p=><Badge status={statusTone[p.status]}>{p.status}</Badge>},{id:'progress',label:'进度',numeric:true,value:p=>p.progress,render:p=><ProgressBar label={`${p.name}进度`} value={p.progress}/>},{id:'amount',label:'合同额（元）',numeric:true,value:p=>p.amount,render:p=>p.amount.toLocaleString('zh-CN')},{id:'due',label:'交付日期',value:p=>p.due}];
 const relatedColumns:DataColumn<RelatedItem>[]=[{id:'name',label:'关联记录',value:r=>r.name,render:r=><Button variant="ghost" size="sm" onClick={()=>setRelatedOpen(r)}>{r.name}</Button>},{id:'kind',label:'类型',value:r=>r.kind},{id:'owner',label:'负责人',value:r=>r.owner},{id:'state',label:'状态',value:r=>r.state,render:r=><Badge status={r.state==='已确认'||r.state==='已复核'?'success':'warning'}>{r.state}</Badge>}];
 const kpis:KpiRowProps['items']=[{label:'合同总额',value:(summary.amount/10000).toFixed(1),unit:'万元',change:`${summary.count} 个项目合同口径`,direction:'flat',trend:sourceRows.length?trend(sourceRows).map(p=>p.value):[]},{label:'交付项目',value:summary.count,unit:'个',change:`${summary.completed} 个已完成`,direction:'flat'},{label:'平均完成度',value:summary.average.toFixed(1),unit:'%',change:'项目完成度算术平均',direction:'flat'},{label:'风险项目',value:summary.risks,unit:'个',change:summary.risks?'需要负责人复核':'暂无风险记录',direction:'flat'}];
 const activity=sourceRows.filter(p=>['存在风险','待验收','已完成'].includes(p.status)).map(p=>({id:p.id,title:p.name,detail:p.status==='存在风险'?'交付存在待核实事项，请负责人查看记录。':p.status==='待验收'?'进入验收准备，等待负责人复核材料。':'已完成当前约定的交付与验收。',actor:p.owner,time:p.status==='已完成'?p.due:'2026-09-28',status:statusTone[p.status],statusLabel:p.status,onOpen:()=>openProject(p.id)})).sort((a,b)=>b.time.localeCompare(a.time)).slice(0,4);
 const insight={text:`${summary.count} 个项目中有 ${summary.risks} 个标记为风险。建议先核对现场数据与交付日期，再决定是否调整计划。`,source:'依据：本页演示项目状态；未连接真实 AI 服务。',actionLabel:'核对风险项目',onReview:()=>openStatus('存在风险')};
 const saveSettings=()=>{if(!draft.workspaceName.trim()){setSettingsError('请填写工作区名称');return;}const next={...draft,workspaceName:draft.workspaceName.trim()};setDraft(next);setSaved(next);setSettingsError('');try{localStorage.setItem(settingsKey,JSON.stringify(next));setSaveMessage('已保存到当前浏览器');setToast('演示设置已保存到当前浏览器');}catch{setSaveMessage('本次会话已保存，浏览器持久存储不可用');setToast('已保留本次会话设置，浏览器无法持久保存');}};
 const settingsPatch=(next:Partial<WorkspaceSettings>)=>setDraft(current=>({...current,...next}));
 const sections:SettingsSectionProps[]=[{id:'workspace-info',title:'工作区资料',description:'为团队识别工作区，指定默认负责人与显示时区。',fields:[{id:'workspace-name',kind:'text',label:'工作区名称',value:draft.workspaceName,onChange:v=>{settingsPatch({workspaceName:v});setSettingsError('');},required:true,maxLength:40,error:settingsError||undefined},{id:'workspace-manager',kind:'select',label:'默认负责人',value:draft.manager,onChange:v=>settingsPatch({manager:v}),options:owners.map(v=>({label:v,value:v})),hint:'用于新建演示项目的默认负责人'},{id:'workspace-timezone',kind:'select',label:'工作区时区',value:draft.timezone,onChange:v=>settingsPatch({timezone:v}),options:[{value:'Asia/Shanghai',label:'中国标准时间 · UTC+8'},{value:'UTC',label:'协调世界时 · UTC'}],hint:'演示保存偏好；既有日期按样本原值显示'}]},{id:'workspace-notifications',title:'通知偏好',description:'只保存本地演示偏好，不会向团队发送消息。',fields:[{id:'risk-alerts',kind:'checkbox',label:'关注风险项目提醒',value:draft.riskAlerts,onChange:v=>settingsPatch({riskAlerts:v}),hint:'供未来业务系统接入时采用'},{id:'daily-digest',kind:'checkbox',label:'接收每日工作摘要',value:draft.digest,onChange:v=>settingsPatch({digest:v}),hint:'演示页面不实际推送通知'}]}];
 const handleNav=(event:MouseEvent<HTMLElement>)=>{if(event.metaKey||event.ctrlKey||event.shiftKey||event.altKey||event.button!==0)return;const target=(event.target as HTMLElement).closest('a');if(!target)return;const next=new URL(target.href).searchParams.get('page');if(recipeCatalog.some(r=>r.id===next)){event.preventDefault();navigate(next as RecipeId);}};
 const startNew=()=>{setNewName('');setNewOwner(saved.manager);setNewError('');setNewOpen(true);};
 const createProject=()=>{const amount=Number(newAmount);if(!newName.trim()||!Number.isFinite(amount)||amount<=0||!newDue){setNewError('请填写项目名称、正数合同金额和交付日期');return;}const id='QK-DEMO-'+Date.now();setRows(current=>[...current,{id,name:newName.trim(),client:newClient,owner:newOwner,amount,progress:0,status:'正常推进',due:newDue,category:'演示',signedMonth:'2026-09'}]);setNewOpen(false);setDataState('ready');setToast('演示项目已创建，刷新页面会恢复原始样本');openProject(id);};
 return <ThemeProvider {...route.settings} className="recipe-demo gallery-workspace">
  <header className="recipe-review-bar"><div><a href={routeUrl(route).replace('view=recipes','view=components')}><ArrowLeft className="qk-icon"/>组件库</a><span className="recipe-stage">阶段 04</span><strong>页面模板验收</strong></div><div className="recipe-style-choice" role="group" aria-label="页面风格">{styleOptions.map(style=><button key={style.theme} aria-pressed={theme===style.theme} onClick={()=>themed({theme:style.theme})}>{String(style.number).padStart(2,'0')} <strong>{style.label}</strong></button>)}</div><details className="recipe-controls"><summary><SlidersHorizontal className="qk-icon"/>预览设置</summary><div><Select label="预览密度" value={route.settings.density} onChange={e=>themed({density:e.target.value as ThemeSettings['density']})} options={[{value:'comfortable',label:'舒适'},{value:'compact',label:'紧凑'}]}/><Select label="预览明暗" value={route.settings.surfaceMode} onChange={e=>themed({surfaceMode:e.target.value as ThemeSettings['surfaceMode']})} options={[{value:'light',label:'浅色'},{value:'dark',label:'深色'},{value:'auto',label:'跟随系统'}]}/><Select label="预览圆角" value={route.settings.radiusScale} onChange={e=>themed({radiusScale:Number(e.target.value) as ThemeSettings['radiusScale']})} options={tokens.parameterPolicy.radiusScale.values.map(v=>({value:String(v),label:v+'×'}))}/><label className="qk-field"><span className="qk-label">强调色相 · {route.settings.accentHue==='brand'?'标准蓝':route.settings.accentHue+'°'}</span><input type="range" aria-label="页面强调色相" min={tokens.parameterPolicy.accentHue.minimum} max={tokens.parameterPolicy.accentHue.maximum} value={route.settings.accentHue==='brand'?Math.round(tokens.parameterPolicy.accentHue.default):route.settings.accentHue} onChange={e=>themed({accentHue:Number(e.target.value)})}/></label><Select label="内容状态" value={dataState} disabled={route.page==='settings'} onChange={e=>setDataState(e.target.value as typeof dataState)} options={[{value:'ready',label:'正常数据'},{value:'loading',label:'加载中'},{value:'empty',label:'空数据'}]}/><Button size="sm" onClick={()=>patch({settings:normalizeTheme({theme})})}><RotateCcw className="qk-icon"/>恢复主题默认</Button></div></details></header>
  <AppShell collapsed={collapsed} onCollapsedChange={setCollapsed} className="recipe-app-shell" brand={<div className="recipe-brand"><Layers3 className="qk-icon"/>{!collapsed&&<span>缺口<small>QUEKOU WORKSPACE</small></span>}</div>} sidebar={<><NavGroup label="工作区" activeId={route.page} onClick={handleNav} items={recipeCatalog.map(r=>{const Icon=pageIcons[r.id];return {id:r.id,label:r.label,href:routeUrl({...route,page:r.id}),icon:<Icon/>,count:r.id==='list'?rows.length:undefined};})}/>{!collapsed&&<div className="recipe-sidebar-note"><span>交付工作台</span><p>从经营概况到项目推进，让每一步都有清楚的落点。</p><small>所有业务数据均为演示。</small></div>}</>} header={<div className="recipe-app-header"><span>{saved.workspaceName}</span><div><Button variant="ghost" size="sm" onClick={()=>setCommandOpen(true)} aria-label="搜索与快捷命令"><Command className="qk-icon"/><span>快捷命令</span><kbd>⌘ K</kbd></Button><Avatar name={saved.manager}/></div></div>}>
   <main ref={mainRef} tabIndex={-1} className="recipe-main" aria-label="工作台页面">
    {route.page==='overview'&&<Overview header={{eyebrow:'OVERVIEW / 经营总览',title:'项目交付总览',description:'截至 2026年9月28日 · 下列指标来自同一份演示项目台账',actions:<Button onClick={()=>navigate('list')} variant="primary">查看全部项目<ArrowUpRight className="qk-icon"/></Button>}} kpis={{theme,items:kpis,insight,loading:dataState==='loading'}} trend={{title:'合同签约趋势',description:`按演示签约月份汇总，累计 ${(summary.amount/10000).toFixed(1)} 万元；计划线为模拟计划。`,unit:'万元',points:sourceRows.length?trend(sourceRows):[],loading:dataState==='loading'}} breakdown={{title:'交付状态分布',description:'按当前项目状态分类',unit:'个',items:sourceRows.length?stages.map(status=>({id:status,label:status,value:sourceRows.filter(p=>p.status===status).length})):[],onSelect:openStatus,loading:dataState==='loading'}} activity={{title:'最近工作动态',description:'演示活动记录 · 点击进入对应项目',items:activity,loading:dataState==='loading'}}/>}
    {route.page==='list'&&<List<WorkProject> header={{eyebrow:'PROJECTS / 项目列表',title:'项目台账',description:'按客户、状态或交付日期定位项目，点击名称查看详情。',actions:<Button variant="primary" onClick={startNew}><Plus className="qk-icon"/>新建项目</Button>}} query={{filters:[{id:'status',label:'项目状态',value:route.query.status,onChange:v=>query({status:v}),options:[{value:'all',label:'全部状态'},...stages.map(v=>({value:v,label:v}))]},{id:'client',label:'客户',value:route.query.client,onChange:v=>query({client:v}),options:[{value:'all',label:'全部客户'},...clientNames.map(v=>({value:v,label:v}))]}],search:route.query.search,onSearchChange:v=>query({search:v}),from:route.query.from,to:route.query.to,onDateChange:query,onReset:()=>patch({query:emptyQuery,listPage:1})}} records={{label:'项目台账',rows:pageRows,columns,getRowId:p=>p.id,total:filtered.length,selectedIds:selection,onSelectionChange:setSelection,onClearSelection:()=>setSelection([]),sort:route.sort,onSortChange:sort=>patch({sort,listPage:1}),loading:dataState==='loading'}} pagination={{page:currentPage,pageSize:route.pageSize,total:filtered.length,selectedCount:selection.length,onPageChange:listPage=>patch({listPage}),onPageSizeChange:pageSize=>patch({pageSize,listPage:1})}}/>}
    {route.page==='detail'&&<Detail<RelatedItem> header={{eyebrow:`PROJECT DETAIL / ${activeProject?.id||'项目详情'}`,title:activeProject?.name||(dataState==='loading'?'正在加载项目':'项目未找到'),description:activeProject?`${activeProject.client} · 业务信息与过程记录放在同一处`:'从项目列表选择一条有效记录。',actions:<Button onClick={()=>navigate('list')}><ArrowLeft className="qk-icon"/>返回项目列表</Button>}} summary={{loading:dataState==='loading',title:'项目概况',description:activeProject?'演示业务对象 · 信息以当前项目台账为准':'当前没有可展示的业务对象',status:activeProject?statusTone[activeProject.status]:'info',statusLabel:activeProject?.status||'暂无记录',fields:activeProject?[{label:'负责人',value:activeProject.owner},{label:'客户',value:activeProject.client},{label:'合同金额',value:activeProject.amount.toLocaleString('zh-CN')+' 元'},{label:'交付日期',value:activeProject.due}]:[],progress:activeProject?.progress,insight:activeProject?{text:activeProject.status==='存在风险'?'当前项目已被标记为风险，建议核对现场数据与交付承诺。':activeProject.status==='已完成'?'当前项目已完成，可回看验收记录与交付过程。':'建议在下一节点前复核交付清单，确保验收材料齐备。',source:'依据：当前项目演示状态；未连接真实 AI 服务。',actionLabel:'查看关联记录',onReview:()=>patch({tab:'related'})}:undefined}} activeTab={route.tab} onTabChange={tab=>patch({tab})} activity={{title:'项目进展',description:'以下为演示过程记录',items:activeProject?timeline(activeProject):[],loading:dataState==='loading'}} related={{title:'关联业务记录',description:'演示清单，可打开查看条目信息。',rows:activeProject?relatedRecords(activeProject):[],columns:relatedColumns,getRowId:r=>r.id,loading:dataState==='loading'}}/>}
    {route.page==='settings'&&<Settings header={{eyebrow:'WORKSPACE / 工作区设置',title:'工作区设置',description:'本页只保存当前浏览器的演示配置。'}} navigation={{items:[{id:'workspace-info',label:'工作区资料',description:'名称、负责人和时区'},{id:'workspace-notifications',label:'通知偏好',description:'需要关注的事项'}],activeId:settingsGroup,onSelect:setSettingsGroup}} sections={sections} dirty={dirty} savedMessage={saveMessage} onSave={saveSettings} onCancel={()=>{setDraft(saved);setSettingsError('');}} danger={{title:'重置演示配置',description:'将工作区资料与通知偏好恢复默认值。',actionLabel:'重置配置',confirmText:'重置演示',confirmDescription:'这会恢复当前浏览器的演示设置。请输入指定文字后确认。',onConfirm:()=>{setDraft(defaultSettings);setSaved(defaultSettings);setSettingsError('');try{localStorage.removeItem(settingsKey);setSaveMessage('已恢复默认演示配置');setToast('演示配置已恢复默认');}catch{setSaveMessage('本次会话已重置，浏览器持久存储不可用');setToast('本次会话已重置，浏览器无法持久保存');}}}}/>} 
   </main>
   <footer className="recipe-page-footer"><span><CheckCircle2 className="qk-icon"/>演示工作区 · 未连接真实业务系统</span><span>{recipeCatalog.find(r=>r.id===route.page)!.name} · {styleOptions.find(s=>s.theme===theme)!.label}</span></footer>
  </AppShell>
  <CommandPalette open={commandOpen} onOpenChange={setCommandOpen} items={[...recipeCatalog.map(r=>({id:r.id,label:`前往${r.label}`,onSelect:()=>navigate(r.id)})),{id:'risks',label:'查看风险项目',onSelect:()=>openStatus('存在风险')} ]}/>
  <Dialog open={newOpen} onOpenChange={setNewOpen} title="新建演示项目" description="仅用于本次演示，刷新页面会恢复初始项目样本。" footer={<><Button onClick={()=>setNewOpen(false)}>取消</Button><Button type="submit" form="new-demo-project" variant="primary">创建演示项目</Button></>}><form id="new-demo-project" className="recipe-new-form" onSubmit={e=>{e.preventDefault();createProject();}}><Input label="项目名称" value={newName} onChange={e=>setNewName(e.target.value)} required maxLength={60} error={newError||undefined}/><Select label="项目客户" value={newClient} onChange={e=>setNewClient(e.target.value)} options={clientNames.map(v=>({value:v,label:v}))}/><Select label="项目负责人" value={newOwner} onChange={e=>setNewOwner(e.target.value)} options={owners.map(v=>({value:v,label:v}))}/><Input label="合同金额（元）" type="number" min="1" step="1" required value={newAmount} onChange={e=>setNewAmount(e.target.value)}/><Input label="交付日期" type="date" required value={newDue} onChange={e=>setNewDue(e.target.value)}/></form></Dialog>
  <Dialog open={!!relatedOpen} onOpenChange={open=>{if(!open)setRelatedOpen(null);}} title={relatedOpen?.name||'关联记录'} description="以下为结构演示，未载入真实业务附件。"><div className="qk-example-stack"><p>记录编号：{relatedOpen?.id}</p><p>负责人：{relatedOpen?.owner}</p><p>类型：{relatedOpen?.kind}</p><Badge status={relatedOpen?.state==='待复核'?'warning':'success'}>{relatedOpen?.state}</Badge></div></Dialog>
  <Toast open={!!toast} onDismiss={()=>setToast('')} title={toast} status="success"/>
 </ThemeProvider>;
}
