const BASE_URL=process.env.WORKBENCH_BASE_URL||'http://127.0.0.1:4173';
const fs=require('node:fs');const assert=require('node:assert/strict');
const {chromium,launchOptions}=require('./browser-runtime.cjs');
const scanContrast=require('./browser-contrast.cjs');
(async()=>{
 const browser=await chromium.launch(launchOptions);const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});page.setDefaultTimeout(8000);
 const report={checks:[],variants:[],responsive:[],errors:[],failedResponses:[]};page.on('pageerror',e=>report.errors.push(e.message));page.on('response',r=>{if(r.status()>=400)report.failedResponses.push({url:r.url(),status:r.status()});});page.on('console',m=>{if(m.type()==='error')report.errors.push({message:m.text(),location:m.location()})});
 const go=async(style=6,mode='light',density='comfortable',extra='')=>{await page.goto(`${BASE_URL}/?view=components&style=${style}&surfaceMode=${mode}&density=${density}${extra}`);await page.waitForSelector('.lab-component');};
 const check=(name,test)=>{assert.ok(test,name);report.checks.push(name);};
 for(const style of [6,7,10])for(const mode of ['light','dark'])for(const density of ['comfortable','compact']){
  await go(style,mode,density);const result=await page.evaluate(scanContrast);const geom=await page.evaluate(()=>({count:document.querySelectorAll('.lab-component').length,row:document.querySelector('.qk-table tbody tr:not(.qk-table-spacer)').getBoundingClientRect().height,domRows:document.querySelectorAll('.qk-table tbody tr:not(.qk-table-spacer)').length,numeric:getComputedStyle(document.querySelector('.qk-kpi-value')).fontVariantNumeric}));
  report.variants.push({style,mode,density,...geom,...result});
  check(`${style}/${mode}/${density}:28 components, bounded table and correct row height`,geom.count===28&&geom.domRows<30&&geom.row===(density==='compact'?40:48)&&geom.numeric==='tabular-nums');
  check(`${style}/${mode}/${density}:no overflow`,!result.overflow);
  if(density==='comfortable')await page.screenshot({path:`qa/phase3/${style}-${mode}.png`});
 }
 fs.writeFileSync('qa/phase3/browser-report.json',JSON.stringify(report,null,2));
 await go();
 const table=page.locator('#component-DataTable'),region=table.getByRole('region'),search=table.getByRole('searchbox');
 await region.focus();await page.keyboard.press('End');await page.waitForTimeout(100);
 check('virtual scroll reaches row 5000',await table.getByRole('checkbox',{name:'选择行 5000',exact:true}).count()===1);
 await region.press('Home');await page.waitForTimeout(100);check('Home returns to first row',await table.getByRole('checkbox',{name:'选择行 0001',exact:true}).count()===1);
 await table.getByRole('button',{name:'合同金额（元）'}).click();check('numeric ascending',await table.locator('tbody tr:not(.qk-table-spacer) .qk-cell').first().innerText()==='演示项目 0001');await table.getByRole('button',{name:'合同金额（元）'}).click();check('numeric descending',await table.locator('tbody tr:not(.qk-table-spacer) .qk-cell').first().innerText()==='演示项目 5000');
 await search.fill('陈明');check('filter searches source values',await table.getByText('1667 行 · 已选择 0 行',{exact:true}).count()===1);await table.getByRole('checkbox',{name:'选择筛选后的全部行',exact:true}).check();check('select all filtered rows including virtual offscreen',await table.getByText('1667 行 · 已选择 1667 行',{exact:true}).count()===1);await table.locator('tbody input[type=checkbox]').first().uncheck();check('partial selection indeterminate',await table.locator('thead input').evaluate(e=>e.indeterminate));
 await search.fill('不存在的项目');check('empty table state',await table.getByText('没有匹配的记录',{exact:true}).isVisible());await search.fill('5000');await table.getByRole('button',{name:'显示全部行',exact:true}).click();check('accessible full list fallback',await table.locator('.qk-data-table').getAttribute('data-virtual')==='false');await table.getByRole('button',{name:'启用虚拟滚动',exact:true}).click();await search.fill('');
 await page.setViewportSize({width:700,height:900});await region.scrollIntoViewIfNeeded();const before=await table.locator('th[data-pinned=true]').boundingBox();await region.evaluate(e=>e.scrollLeft=200);const after=await table.locator('th[data-pinned=true]').boundingBox();check('first column stays pinned horizontally',Math.abs(before.x-after.x)<1&&await region.evaluate(e=>e.scrollLeft)>0);await page.setViewportSize({width:1440,height:1000});
 const openDialog=page.getByRole('button',{name:'打开确认弹窗',exact:true});await openDialog.click();const dialog=page.getByRole('dialog',{name:'确认项目名称',exact:true});check('dialog visible',await dialog.isVisible());for(let i=0;i<9;i++){await page.keyboard.press('Tab');check('dialog traps Tab '+i,await dialog.evaluate(e=>e.contains(document.activeElement)));}await page.keyboard.press('Escape');check('Escape closes dialog and returns focus',!(await dialog.isVisible())&&await openDialog.evaluate(e=>e===document.activeElement));
 await openDialog.click();await dialog.getByLabel('新的项目名称').fill('验收用名称');await dialog.getByRole('button',{name:'确认名称',exact:true}).click();check('dialog controlled value retained',await page.getByText('演示已确认：验收用名称',{exact:true}).isVisible());
 const drawerTrigger=page.getByRole('button',{name:'打开项目抽屉'});await drawerTrigger.click();check('drawer modal',await page.getByRole('dialog',{name:'项目概况',exact:true}).isVisible());await page.keyboard.press('Escape');check('drawer focus returned',await drawerTrigger.evaluate(e=>e===document.activeElement));
 const tooltip=page.getByRole('button',{name:'查看口径说明',exact:true});await tooltip.focus();check('tooltip keyboard description',await page.getByRole('tooltip').isVisible());await tooltip.hover();await page.mouse.move(0,0);check('tooltip stays while keyboard focused after pointer leaves',await page.getByRole('tooltip').isVisible());await page.keyboard.press('Escape');check('tooltip Escape dismissal',await page.getByRole('tooltip').count()===0);
 const pop=page.getByRole('button',{name:'打开显示选项',exact:true});await pop.click();check('popover focuses first control',await page.getByRole('checkbox',{name:'显示项目负责人',exact:true}).evaluate(e=>e===document.activeElement));await page.keyboard.press('Escape');check('popover Escape returns focus',await pop.evaluate(e=>e===document.activeElement)&&await page.getByRole('region',{name:'显示选项',exact:true}).count()===0);
 await page.getByRole('checkbox',{name:'我已核对交付清单',exact:true}).focus();await page.keyboard.press('Space');check('checkbox keyboard Space',await page.getByRole('checkbox',{name:'我已核对交付清单',exact:true}).isChecked());
 await page.getByRole('button',{name:'移除本周交付'}).click();check('tag removable',await page.getByRole('button',{name:'恢复标签',exact:true}).isVisible());await page.getByRole('button',{name:'恢复标签',exact:true}).click();
 await page.getByRole('button',{name:'收起侧栏',exact:true}).click();check('sidebar collapses',await page.locator('.qk-shell').getAttribute('data-collapsed')==='true');await page.getByRole('button',{name:'展开侧栏',exact:true}).click();
 await page.getByRole('button',{name:'打开快捷命令 · ⌘ K',exact:true}).focus();await page.keyboard.press('Control+k');const command=page.getByRole('combobox',{name:'搜索快捷命令',exact:true});check('Ctrl K opens command palette',await command.isVisible());await command.press('ArrowDown');await command.press('Enter');check('command keyboard selects action',await page.getByText('演示已执行：查看待办',{exact:true}).isVisible());await page.keyboard.press('Meta+k');await command.fill('无匹配');check('command empty result',await page.getByText('没有匹配的命令',{exact:true}).isVisible());await page.keyboard.press('Escape');
 const pager=page.locator('#component-Pagination');await pager.getByRole('button',{name:'末页',exact:true}).click();check('pagination end guards',await pager.getByRole('button',{name:'下一页',exact:true}).isDisabled());await pager.getByRole('button',{name:'首页',exact:true}).click();check('pagination start guards',await pager.getByRole('button',{name:'上一页',exact:true}).isDisabled());
 const filters=page.locator('#component-FilterBar');await filters.getByLabel('交付状态',{exact:true}).selectOption('accepted');await filters.getByLabel('搜索',{exact:true}).fill('审查');await filters.getByLabel('开始日期').fill('2026-09-01');await filters.getByRole('button',{name:'重置筛选'}).click();check('filter reset clears values',await filters.getByLabel('搜索',{exact:true}).inputValue()===''&&await filters.getByLabel('开始日期').inputValue()===''&&await filters.getByLabel('交付状态',{exact:true}).inputValue()==='all');
 await page.getByRole('button',{name:'显示操作反馈',exact:true}).click();const closeToast=page.getByRole('button',{name:'关闭通知',exact:true});await closeToast.focus();await closeToast.hover();await page.mouse.move(0,0);await page.waitForTimeout(3800);check('toast remains while focused after mouse leave',await closeToast.isVisible());await closeToast.click();check('toast dismiss',await closeToast.count()===0);
 for(const style of [6,7,10])for(const mode of ['light','dark']){await page.setViewportSize({width:390,height:844});await go(style,mode,'compact');const result=await page.evaluate(scanContrast);report.responsive.push({style,mode,...result});check(`${style}/${mode} mobile no overflow`,!result.overflow);if(mode==='dark'){await page.locator('#component-DataTable').scrollIntoViewIfNeeded();await page.screenshot({path:`qa/phase3/${style}-mobile-table.png`});}}
 await page.setViewportSize({width:1440,height:1000});await go(7,'auto');await page.emulateMedia({colorScheme:'dark'});const dark=await page.locator('.component-lab').evaluate(e=>getComputedStyle(e).backgroundColor);await page.emulateMedia({colorScheme:'light'});const light=await page.locator('.component-lab').evaluate(e=>getComputedStyle(e).backgroundColor);check('auto follows OS live',dark!==light);
 await page.getByLabel('组件圆角程度').selectOption('1.5');await page.getByLabel('组件强调色相').fill('230');await page.reload();check('theme settings persist in URL',await page.getByLabel('组件圆角程度').inputValue()==='1.5'&&await page.getByLabel('组件强调色相').inputValue()==='230');
 await page.locator('#component-KpiCard').scrollIntoViewIfNeeded();await page.screenshot({path:'qa/phase3/data-detail.png'});await page.locator('#component-AppShell').scrollIntoViewIfNeeded();await page.screenshot({path:'qa/phase3/workbench-detail.png'});
 report.contrastPassed=[...report.variants,...report.responsive].every(r=>r.violations.length===0&&r.semanticPairs.every(p=>p.ratio>=p.min));report.result=report.errors.length===0&&report.contrastPassed?'passed':'review';fs.writeFileSync('qa/phase3/browser-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({result:report.result,checks:report.checks.length,variants:report.variants.length,responsive:report.responsive.length,errors:report.errors,failedResponses:report.failedResponses,contrastViolations:report.variants.flatMap(r=>r.violations.map(v=>({style:r.style,mode:r.mode,...v}))),minContrast:Math.min(...report.variants.map(v=>v.minContrast))},null,2));await browser.close();if(report.result!=='passed')process.exitCode=1;
})().catch(e=>{console.error(e);process.exit(1)});
