import {readFile,readdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {flattenColors} from '../design/preview-parameters.mjs';
const tokens=JSON.parse(await readFile('design/tokens.json','utf8'));
const files=['starter/src/main.tsx','starter/src/styles.css','app/styles.css','app/switcher.tsx','app/specimens/Workbench.tsx','app/data.ts','app/theme-review.tsx','app/component-lab.tsx','app/component-lab.css','packages/ui/src/styles.css',...(await readdir('packages/ui/src/components')).filter(n=>n.endsWith('.tsx')).map(n=>'packages/ui/src/components/'+n),'packages/ui/src/internal/foundation.tsx','packages/ui/src/blocks.css',...(await readdir('packages/ui/src/blocks')).filter(n=>n.endsWith('.tsx')).map(n=>'packages/ui/src/blocks/'+n),...(await readdir('packages/ui/src/recipes')).filter(n=>n.endsWith('.tsx')).map(n=>'packages/ui/src/recipes/'+n),...(await readdir('app/workbench')).filter(n=>/\.(tsx|css)$/.test(n)).map(n=>'app/workbench/'+n)];
const source=(await Promise.all(files.map(f=>readFile(f,'utf8')))).join('\n');
assert(!/(?:bg|text|border|ring|fill|stroke)-(?:slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-\d/.test(source));
assert(!/#[0-9a-fA-F]{3,8}\b|(?:hsl|rgb|oklch)\(/.test(source),'literal colors may only exist in tokens');
assert(!/style=\{|styled\.|@emotion|styled-components/.test(source),'no CSS in JS');
const css=(await Promise.all(files.filter(f=>f.endsWith('.css')).map(f=>readFile(f,'utf8')))).join('\n');
assert(!/(?:font-size|border-radius|padding|margin|gap)\s*:\s*\d+(?:px|rem)/.test(css),'visual values must reference tokens');
const names=new Set([...Object.keys(tokens.common),...Object.keys(tokens.gallery),...Object.values(tokens.themes).flatMap(Object.keys),...Object.values(tokens.systems).flatMap(s=>[...Object.keys(s.structure),...Object.keys(flattenColors(s.colors.light)),...Object.keys(s.effects.light),...Object.keys(s.density.compact)])]);
for(const ref of source.matchAll(/var\(--([a-zA-Z0-9_-]+)/g))assert(names.has(ref[1]),`undefined token ${ref[1]}`);
assert.equal((await readdir('app/specimens')).filter(n=>/^Sample\d\d.tsx$/.test(n)).length,10);
assert.equal(tokens.styles.length,10);assert.equal(Object.keys(tokens.themes).length,8);assert.equal(Object.keys(tokens.systems).length,3);assert.equal(tokens.phase,5);
const pkg=JSON.parse(await readFile('package.json','utf8'));
assert.equal(pkg.dependencies.react,'18.3.1');
assert.deepEqual(Object.keys(pkg.dependencies).sort(),['lucide-react','react','react-dom']);
assert.match(css,/font-variant-numeric:\s*tabular-nums/);
const report={result:'passed',samples:10,themeVariants:14,sourceFiles:files,checks:['semantic color classes','no color literals in view code','no CSS-in-JS','token font/radius/spacing','token references defined','no UI library','React 18','tabular numerals']};
await writeFile('qa/token-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
