import {forwardRef,useRef,useState,useMemo,useLayoutEffect,useContext,type ForwardedRef,type RefAttributes,type ReactElement,type ReactNode,type HTMLAttributes} from 'react';
import {ArrowDownUp} from 'lucide-react';
import {cx,useThemeAttributes,useMergedRef,useControllable,ThemeContext,uiTokens,type ThemeOverrides} from '../internal/foundation';
import {Input} from './Input';
import {Checkbox} from './Checkbox';
import {Button} from './Button';
import {EmptyState} from './EmptyState';
export interface DataColumn<T> {id:string;label:string;value:(row:T)=>string|number|null|undefined;render?:(row:T)=>ReactNode;sortable?:boolean;numeric?:boolean}
export interface TableSort {column:string;direction:'asc'|'desc'}
export interface DataTableProps<T> extends Omit<HTMLAttributes<HTMLDivElement>,'onSelect'>,ThemeOverrides {rows:readonly T[];columns:readonly DataColumn<T>[];getRowId:(row:T)=>string;label:string;showToolbar?:boolean;showFooter?:boolean;selectionLabel?:string;selectable?:boolean;selectedIds?:readonly string[];onSelectionChange?:(ids:string[])=>void;sort?:TableSort|null;onSortChange?:(sort:TableSort)=>void;search?:string;onSearchChange?:(search:string)=>void;pinFirstColumn?:boolean;virtual?:boolean;loading?:boolean}
function DataTableInner<T>({rows,columns,getRowId,label,showToolbar=true,showFooter=true,selectionLabel="选择筛选后的全部行",selectable=false,selectedIds,onSelectionChange,sort:sortProp,onSortChange,search:searchProp,onSearchChange,pinFirstColumn=true,virtual=true,loading=false,density,surfaceMode,className,...rest}:DataTableProps<T>,ref:ForwardedRef<HTMLDivElement>){
 const attrs=useThemeAttributes({density,surfaceMode}),theme=useContext(ThemeContext);const outer=useRef<HTMLDivElement|null>(null),scroll=useRef<HTMLDivElement>(null),merged=useMergedRef(ref,outer);
 const [search,setSearch]=useControllable(searchProp,'',onSearchChange);const [sort,setSort]=useControllable<TableSort|null>(sortProp,null,s=>{if(s)onSortChange?.(s);});const [selection,setSelection]=useControllable<readonly string[]>(selectedIds,[],ids=>onSelectionChange?.([...ids]));
 const [allRows,setAllRows]=useState(false),[offset,setOffset]=useState(0),[dimensions,setDimensions]=useState({row:parseFloat(uiTokens['row-height']),viewport:0,header:0});
 useLayoutEffect(()=>{const el=scroll.current;if(!el)return;const measure=()=>{const cs=getComputedStyle(el);setDimensions({row:parseFloat(cs.getPropertyValue('--row-height')),viewport:el.clientHeight,header:parseFloat(cs.getPropertyValue('--table-header-height'))});};measure();const observer=new ResizeObserver(measure);observer.observe(el);return()=>observer.disconnect();},[density,theme.density,allRows,virtual]);
 const filtered=useMemo(()=>{const needle=search.trim().toLocaleLowerCase();const result=rows.filter(row=>!needle||columns.some(c=>String(c.value(row)??'').toLocaleLowerCase().includes(needle)));const col=columns.find(c=>c.id===sort?.column);if(col&&sort)result.sort((a,b)=>{const x=col.value(a)??'',y=col.value(b)??'';const n=typeof x==='number'&&typeof y==='number'?x-y:String(x).localeCompare(String(y),'zh-CN',{numeric:true});return n*(sort.direction==='asc'?1:-1);});return result;},[rows,columns,search,sort]);
 useLayoutEffect(()=>{if(scroll.current)scroll.current.scrollTop=0;setOffset(0);},[search,sort,rows]);
 const isVirtual=virtual&&!allRows,overscan=Number(uiTokens['virtual-overscan']),rowHeight=dimensions.row||parseFloat(uiTokens['row-height']);
 const first=isVirtual?Math.max(0,Math.min(Math.max(0,filtered.length-1),Math.floor(Math.max(0,offset-dimensions.header)/rowHeight)-overscan)):0;
 const end=isVirtual?Math.min(filtered.length,first+Math.ceil(dimensions.viewport/rowHeight)+overscan*2):filtered.length;
 const visible=filtered.slice(first,end),colSpan=columns.length+(selectable?1:0),selectedSet=new Set(selection),every=filtered.length>0&&filtered.every(r=>selectedSet.has(getRowId(r))),some=filtered.some(r=>selectedSet.has(getRowId(r)));
 const selectAll=(checked:boolean)=>{const ids=new Set(selection);for(const row of filtered){if(checked)ids.add(getRowId(row));else ids.delete(getRowId(row));}setSelection([...ids]);};
 const spacer=(height:number,key:string)=><tr key={key} aria-hidden="true" className="qk-table-spacer"><td colSpan={colSpan}><svg height={height} width="1" aria-hidden="true"/></td></tr>;
 return <div {...rest} {...attrs} ref={merged} className={cx('qk-data-table qk-panel',className)} data-virtual={isVirtual} data-selectable={selectable} aria-busy={loading||undefined}>
  {showToolbar&&<div className="qk-table-toolbar"><Input label="搜索表格" aria-label={`${label}搜索`} type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索任意列"/><span className="qk-muted" aria-live="polite">{filtered.length} 行 · 已选择 {selection.length} 行</span>{virtual&&<Button size="sm" onClick={()=>setAllRows(!allRows)} aria-pressed={allRows}>{allRows?'启用虚拟滚动':'显示全部行'}</Button>}</div>}
  <div ref={scroll} className="qk-table-scroll" role="region" aria-label={`${label}可滚动表格`} tabIndex={0} onScroll={e=>setOffset(e.currentTarget.scrollTop)} onKeyDown={e=>{if(e.target!==e.currentTarget)return;const el=e.currentTarget;const jumps:Record<string,number>={ArrowDown:el.scrollTop+rowHeight,ArrowUp:el.scrollTop-rowHeight,PageDown:el.scrollTop+el.clientHeight,PageUp:el.scrollTop-el.clientHeight,Home:0,End:el.scrollHeight};if(e.key in jumps){e.preventDefault();el.scrollTop=jumps[e.key];}}}>
   <table className="qk-table" aria-rowcount={filtered.length+1}><caption className="qk-sr-only">{label}，{isVirtual?'虚拟滚动；可用方向键、PageDown、Home、End，或显示全部行':'完整列表'}</caption><thead><tr>{selectable&&<th className="qk-select-col"><Checkbox label={selectionLabel} className="qk-checkbox-icon" checked={every} indeterminate={some&&!every} disabled={!filtered.length||loading} onChange={e=>selectAll(e.target.checked)}/></th>}{columns.map((col,i)=><th key={col.id} scope="col" data-pinned={pinFirstColumn&&i===0} data-numeric={col.numeric} aria-sort={sort?.column===col.id?(sort.direction==='asc'?'ascending':'descending'):'none'}>{col.sortable!==false?<button type="button" onClick={()=>setSort({column:col.id,direction:sort?.column===col.id&&sort.direction==='asc'?'desc':'asc'})}>{col.label}<ArrowDownUp className="qk-icon" aria-hidden="true"/></button>:col.label}</th>)}</tr></thead>
   <tbody>{isVirtual&&first>0&&spacer(first*rowHeight,'top')}{visible.map((row,index)=>{const id=getRowId(row);return <tr key={id} aria-rowindex={first+index+2} aria-selected={selectable?selectedSet.has(id):undefined} data-selected={selectedSet.has(id)}>{selectable&&<td className="qk-select-col"><Checkbox label={`选择行 ${id}`} className="qk-checkbox-icon" checked={selectedSet.has(id)} disabled={loading} onChange={e=>{const ids=new Set(selection);if(e.target.checked)ids.add(id);else ids.delete(id);setSelection([...ids]);}}/></td>}{columns.map((col,i)=><td key={col.id} data-pinned={pinFirstColumn&&i===0} data-numeric={col.numeric}><div className="qk-cell">{col.render?col.render(row):col.value(row)??'—'}</div></td>)}</tr>;})}{isVirtual&&end<filtered.length&&spacer((filtered.length-end)*rowHeight,'bottom')}</tbody></table>
   {!filtered.length&&<EmptyState title={loading?'正在载入数据':'没有匹配的记录'} description={loading?'请稍候。':'调整关键词后重试。'}/>}
  </div>{showFooter&&<div className="qk-table-footer">{loading?'正在更新数据':`显示 ${filtered.length?first+1:0}–${end} / ${filtered.length} 行`}{isVirtual&&<span>虚拟滚动已启用 · 首列可固定</span>}</div>}
 </div>;
}
export const DataTable=forwardRef(DataTableInner) as <T>(props:DataTableProps<T>&RefAttributes<HTMLDivElement>)=>ReactElement;
